proto_library(
    name = "dmtool_proto",
    srcs = ["dmtool.proto"],
)

java_proto_library(
    name = "dmtool_java_proto",
    deps = ["//proto:dmtool_proto"],
    visibility = ["//visibility:public"],
)
